site_name: IMA World Health ODK Documentation

nav:
  - 'Introduction' : '01-introduction.md'
  - 'Installation de l’application' : '02-installation.md'
  - 'Connexion à son compte ODK Collect' : '03-connnection-to-server.md'
  - 'Téléchargement des formulaires' : '04-download-forms.md'
  - 'Remplir un formulaire' : '05-completing-forms.md'

theme:
  name : 'material'
